### ISSUE TITLE
Unable to build OS X target w. Carthage

### ISSUE THREAD

**Issue by carloe** [tristanhimmelman/AlamofireObjectMapper#17]
I am just starting to transition from pods to carthage, so it is highly possible I am doing something wrong :smile: 

Running `carthage update` fails with the following error while building the os x target:

```
The following build commands failed:
	CompileSwift normal x86_64 /Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapperTests/AlamofireObjectMapperTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/Alamofire/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/ObjectMapper/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/Alamofire/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/ObjectMapper/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/Alamofire/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/ObjectMapper/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/Alamofire/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/Carthage/Checkouts/ObjectMapper/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/dev/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
/Users/dev/Documents/Projects/swift/PGW-OSX/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapperTests/AlamofireObjectMapperTests.swift:11:8: error: no such module 'ObjectMapper'
A shell task failed with exit code 65
```

My `Carthage` file is bare-bones:

```
github "tristanhimmelman/AlamofireObjectMapper" ~> 0.7
```

I am getting the same `no such module 'ObjectMapper'` error in the IDE when I clone the `AlamofireObjectMapper` repo, run `carthage update`, open the workspace and then set the target to `AlamofireObjectMapper OS X`. Hitting build makes the error disappear, and I am able to run the tests afterwards. 

I am running XCode 6.4 (6E35b)

Any ideas?

**Comment by MattesGroeger** [comment]
I'm running into the same issue

**Comment by clarisli** [comment]
Same here.

**Comment by rhunt222** [comment]
Same.

**Comment by ynnckcmprnl** [comment]
This still occurs when targeting iOS.

**Comment by tristanhimmelman** [comment]
I'm not sure what is causing this issue... however, it is not occurring on the swift-2.0 branch which will soon be merged into master.

**Comment by ynnckcmprnl** [comment]
I tried using the 0.8 version in combination with Xcode 7 GM, but am still running into related issues.

```
github "tristanhimmelman/AlamofireObjectMapper" ~> 0.8
```

```
*** Building scheme "AlamofireObjectMapper iOS" in AlamofireObjectMapper.xcworkspace
ld: warning: directory not found for option '-F/Users/Yannick/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/Yannick/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/Yannick/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/Yannick/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-dauotuqewdtvbqbcptlcgtwkqndr/Build/Products/Debug-iphoneos'
```

**Comment by tristanhimmelman** [comment]
@ynnckcmprnl These warnings should be resolved in my next release

**Comment by manuelolmos** [comment]
@tristanhimmelman it's still happening also in swift2 branch. v.0.9.3

<img width="1269" alt="screen shot 2015-10-11 at 9 23 08 pm" src="https://cloud.githubusercontent.com/assets/1574095/10420012/55bd1842-705e-11e5-8f1a-f1607d457f09.png">
