### ISSUE TITLE
Alamofire 5.0.0-rc.2 compatible version?

### ISSUE THREAD

**Issue by SagarUnagar** [tristanhimmelman/AlamofireObjectMapper#286]
Hello all,

Which version is compatible with `Alamofire 5.0.0-rc.2`?

Best

**Comment by maoobordel** [comment]
+1

**Comment by SagarUnagar** [comment]
Pods,

```
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 6.1.0'
```

Errors,

![image](https://user-images.githubusercontent.com/16893693/65308830-7f67ab80-dba8-11e9-82d0-6478f5cfb0ca.png)

**Comment by RomanPodymov** [comment]
Hello @SagarUnagar @maoobordel 
I created [a pull request with Alamofire 5.0.0-rc.2 support](https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/284). If you use CocoaPods just replace `pod 'AlamofireObjectMapper', '~> 6.1.0'` with `pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master'` in your Podfile.

**Comment by SagarUnagar** [comment]
@RomanPodymov Thank you for your fixes. Its seems working fine now. When will be it merged to the main branch?

**Comment by RomanPodymov** [comment]
@SagarUnagar Probably this question is for @tristanhimmelman.

**Comment by ozgur** [comment]
@tristanhimmelman any update on this?

**Comment by wixvii** [comment]
@RomanPodymov I have some issues on your PR 
<img width="259" alt="Screen Shot 2019-09-23 at 15 13 14" src="https://user-images.githubusercontent.com/17345325/65424661-bfcb6180-de14-11e9-9e06-794dadb55248.png">

**Comment by RomanPodymov** [comment]
Hello @wixvii 
Can you reproduce this issue on AlamofireObjectMapper 6.1.0?

**Comment by wixvii** [comment]
@RomanPodymov yeah both have the same issue

**Comment by ozgur** [comment]
@wixvii I believe it should be fixed in https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/288

Could you please check if the problem has been fixed?

**Comment by chanmomo413** [comment]
I have the same problem.
I use Swift5 and Xcode11.

pod 'AlamofireObjectMapper', '~> 6.1.0' and pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master' fail.

**Comment by RomanPodymov** [comment]
Hello @wixvii @ozgur @chanmomo413 
Can you please share an example project where you can reproduce these errors?

**Comment by wixvii** [comment]
@chanmomo413 I use legacy build system and it fixed it.

**Comment by maoobordel** [comment]
same problem as wixvii , but legacy build system didnt helped. :(

**Comment by maoobordel** [comment]
is it possible to merge that pull request ? because i cannot add fork repo to podspec dependency. Thank you so much guys

**Comment by tristanhimmelman** [comment]
I have just merged and released the PR to resolve this. Thanks @RomanPodymov

**Comment by suryakantkachhi** [comment]
Hi

I'm still getting this error with below pods, i tried all mentioned Git master but nothing working.

Getting this error in XCODE11 with swift 5.

When i use AFDataRequest instead of DataRequest then issue go away. i don't whether its the correct approach to resolve the same ?

Please Help me to get out of it. thanks

pod 'Alamofire', '~> 5.0.0-rc.2'
pod 'ObjectMapper', '~> 3.4'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'master'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/ozgur/AlamofireObjectMapper.git', :branch => 'master'
pod 'AlamofireObjectMapper', '~> 6.2.0'
#pod 'AlamofireObjectMapper', '~> 5.2'
#pod 'Alamofire', '~> 4.0.0'
![Screenshot 2019-11-03 at 7 16 23 PM](https://user-images.githubusercontent.com/13748232/68086136-78ea7600-fe6e-11e9-85fa-1378a4e9bc25.png)

**Comment by RomanPodymov** [comment]
Hello @suryakantkachhi 
**AlamofireObjectMapper 6.2.0** uses **Alamofire 5.0.0-rc.2**.
As you can see in [Alamofire 5.0.0-rc.1 release notes](https://github.com/Alamofire/Alamofire/releases/tag/5.0.0-rc.1) 2 new typealiases were added (`AFDataResponse` and `AFDownloadResponse`). So you can use `AFDataResponse<LoginDSModel>` instead of `DataResponse<LoginDSModel, AFError>`.
If you want to use **Alamofire 5.0.0-rc.3** replace `pod 'AlamofireObjectMapper'` with `pod 'AlamofireObjectMapper', :git => https://github.com/RomanPodymov/AlamofireObjectMapper.git` in your Podfile.

**Comment by suryakantkachhi** [comment]
Hello @RomanPodymov i have used Alamofire 5.0.0-rc.3 replaced pod 'AlamofireObjectMapper' with pod 'AlamofireObjectMapper', :git => https://github.com/RomanPodymov/AlamofireObjectMapper.git in Podfile hence encountered with below error.

It seems like source master branch doesn't exist?

[!] Error installing AlamofireObjectMapper
[!] Failed to download 'AlamofireObjectMapper': [!] /usr/local/bin/git clone https://github.com/RomanPodymov/AlamofireObjectMapper.git /var/folders/tb/ly7jxws951zbtkffmcyycf2c0000gn/T/d20191103-1218-17hf24n --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/tb/ly7jxws951zbtkffmcyycf2c0000gn/T/d20191103-1218-17hf24n'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
![Screenshot 2019-11-03 at 9 17 27 PM](https://user-images.githubusercontent.com/13748232/68087865-8a884980-fe7f-11e9-817d-a4b4feee11da.png)

**Comment by RomanPodymov** [comment]
Hello @suryakantkachhi 
Try again please, I restored this branch.

**Comment by suryakantkachhi** [comment]
Much thanks 👍 @RomanPodymov  now its installed.
![Screenshot 2019-11-03 at 10 26 33 PM](https://user-images.githubusercontent.com/13748232/68088865-25395600-fe89-11e9-87d0-89b59e48ce82.png)
